version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/resources/logos"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"

  - package-ecosystem: "npm"
    directory: "/packages/errors"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"

  - package-ecosystem: "npm"
    directory: "/packages/crash-handler"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"

  - package-ecosystem: "npm"
    directory: "/packages/log-error"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"

  - package-ecosystem: "npm"
    directory: "/packages/logger"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"

  - package-ecosystem: "npm"
    directory: "/packages/middleware-log-errors"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"

  - package-ecosystem: "npm"
    directory: "/packages/middleware-render-error-info"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"

  - package-ecosystem: "npm"
    directory: "/packages/serialize-error"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"

  - package-ecosystem: "npm"
    directory: "/packages/serialize-request"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"

  - package-ecosystem: "npm"
    directory: "/packages/opentelemetry"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "fix:"
      prefix-development: "chore:"
