version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/errors"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/log-error"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/middleware-log-errors"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/serialize-error"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/serialize-request"
    schedule:
      interval: "daily"
